### PR TITLE
Add Kamelet example

### PR DESCRIPTION
**Pull request by zhfeng**
Note that the `main` branch points at the latest stable Camel Quarkus release.
Pull requests should be generally send against the `camel-quarkus-main` branch pointing at the current Camel Quarkus SNAPSHOT.

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Comment by jamesnetherton** [comment]
Please run `./mvnw org.l2x6.cq:cq-maven-plugin:0.33.0:update-examples-json` to update the examples JSON file for the website.

Also please add the project to `.github/test-categories.yaml`.

**Comment by aldettinger** [comment]
@zhfeng , I was working on https://github.com/apache/camel-quarkus/issues/2630 and realized Chuck Norris is actually a better example :)
I ended up rebasing this PR in commit https://github.com/aldettinger/camel-quarkus-examples/commit/d09d743bb67bd07c6713ce3a0520e97e7ad1d63e.
Are you ok if I try to force the result push here ?

**Comment by zhfeng** [comment]
@aldettinger Nice - It looks good to me !

**Comment by aldettinger** [comment]
It didn't make it, so I've opened https://github.com/apache/camel-quarkus-examples/pull/43. Let see if that's ok.

**Comment by zhfeng** [comment]
I rebase and resolve the conflicts. hope this works !

**Comment by aldettinger** [comment]
So, there are issues related to 2.0.0-SNAPSHOT versions that does not exist + other examples modified while they should not. I guess the root cause is that I forced push based on main and not camel-quarkus-main thus messing up the PR.

From there, I would suggest to restart from camel-quarkus-main, cherry-pick the commit and force push. Or maybe another PR based on camel-quarkus-main.

@zhfeng What do you think ? Would you like to do it or I can proceed ?

**Comment by aldettinger** [comment]
ok, the build issue seems transient and unrelated. Merging then.

**Pull request merged**
