### PR TITLE
Add saga example

### PR DESCRIPTION
**Pull request by zhfeng**
Fix https://github.com/apache/camel-quarkus/issues/5668

Note that the `main` branch points at the latest stable Camel Quarkus release.
Pull requests should be generally send against the `camel-quarkus-main` branch pointing at the current Camel Quarkus SNAPSHOT.

### CODE REVIEW

**Comment by jamesnetherton** [comment]
I think you'll need to tweak the script that generates the test categories:

https://github.com/apache/camel-quarkus-examples/blob/main/.github/generate-test-groups.groovy

It'll recursively find all `pom.xml` files. I think we only want the top level ones from each project.

**Review by jamesnetherton — COMMENTED** [review]
Looks ok to me.

I guess there are no tests because it's tricky to do since there are 3 separate apps?

Would be good to create an issue to follow up and investigate adding tests for the future.

**Comment by zhfeng** [comment]
Yeah, there are 3 apps and also depends on `artemis` and `narayana-lra-coordinator`. I will take a look to see if it is possible to add a integration test.

**Comment by zhfeng** [comment]
OK, I create a following issue https://github.com/apache/camel-quarkus/issues/6195

**Pull request merged**
