### PR TITLE
Triggering time less often and fixing README.adoc

### PR DESCRIPTION
**Pull request by shravaniPshetty**
Note that the `main` branch points at the latest stable Camel Quarkus release.
Pull requests should be generally send against the `camel-quarkus-main` branch pointing at the current Camel Quarkus SNAPSHOT.

### CODE REVIEW

**Comment by spatnity** [comment]
Can somebody give an insight for this failing check here?

**Comment by jamesnetherton** [comment]
> Can somebody give an insight for this failing check here?

Probably a flaky test - I have run the job again.

**Review by aldettinger — APPROVED** [review]
Looks good to me :+1: Maybe an improvement in a next pr could be to skip tests when executing `mvn package` and `mvn package -Dnative`.

**Comment by spatnity** [comment]
Thanks @aldettinger and @jamesnetherton

**Comment by spatnity** [comment]
> Looks good to me 👍 Maybe an improvement in a next pr could be to skip tests when executing `mvn package` and `mvn package -Dnative`.

Yeah sure!

**Pull request merged**
