### PR TITLE
Fix message_bridge example crash scenario

### PR DESCRIPTION
**Pull request by zhfeng**
Note that the `main` branch points at the latest stable Camel Quarkus release.
Pull requests should be generally send against the `camel-quarkus-main` branch pointing at the current Camel Quarkus SNAPSHOT.

### CODE REVIEW

**Comment by zhfeng** [comment]
Hi @avano ,

Can you check this fix? I add `FirstResource` interface in `DummyXAResource` and it can be marked as the first resource to commit during the 2PC.
So the WARN messages are not happening when the application restart after crashing.

**Review by oscerd — APPROVED** [review]

**Comment by zhfeng** [comment]
@jamesnetherton CI is failing and it has to wait for camel-quarkus `3.6.0` release?

**Comment by jamesnetherton** [comment]
> @jamesnetherton CI is failing and it has to wait for camel-quarkus `3.6.0` release?

It's because the CQ `main` branch has moved on to `3.7.0-SNAPSHOT`. So the example projects will need to be updated to point at that.

**Review by avano — APPROVED** [review]

**Comment by avano** [comment]
thanks @zhfeng ! looks good to me

**Comment by zhfeng** [comment]
@jamesnetherton are you going to move `main` branch to `3.7.0-SNAPSHOT`?

**Review by aldettinger — APPROVED** [review]

**Comment by jamesnetherton** [comment]
> @jamesnetherton are you going to move main branch to 3.7.0-SNAPSHOT?

If this PR is not urgent to merge, then I can incorporate the commit it into the 3.6.0 upgrade after the Quarkus Platform is released on Wednesday.

**Comment by zhfeng** [comment]
Sure, no problem!

**Pull request closed without merging**
