### PR TITLE
Explicitly set locale with en_US

### PR DESCRIPTION
**Pull request by zhfeng**
Note that the `main` branch points at the latest stable Camel Quarkus release.
Pull requests should be generally send against the `camel-quarkus-main` branch pointing at the current Camel Quarkus SNAPSHOT.

### CODE REVIEW

**Comment by aldettinger** [comment]
Interesting, do we by any chance remind what kind of issue it generate when we don't force english locale please ?

**Comment by zhfeng** [comment]
Well, it's just failing with the test like
```
ERROR] Failures: 
[ERROR]   RouteTest.unstructuredFileTranscriptsAreTransformedToPojos:70 1 expectation failed.
JSON path pojos[0].customerBirthday doesn't match.
Expected: is "10 July 1986"
  Actual: 10 七月 1986

[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

```

**Comment by ppalaga** [comment]
@zhfeng sounds like it fails for you in JVM mode on a machine where the default locale is non-english, right? (I just wonder whether it has to do with some recent changes in GraalVM or whether it is an old issue that just popped up now?)

**Comment by aldettinger** [comment]
It smells non localized [String.format](https://github.com/apache/camel-quarkus-examples/blob/main/data-extract-langchain4j/src/main/java/org/acme/extraction/CustomPojoExtractionService.java#L48).

Could you please try to use the localized format override, ala `String.format(Locale.US,...` ? That way, it would give indication whether GraalVM recent changes are involved and it could also work outside of surefire.

**Comment by zhfeng** [comment]
Yeah, I will try `String.format`.

**Comment by zhfeng** [comment]
@aldettinger @ppalaga OK, it works with using `en_US`  in String.format

**Comment by zhfeng** [comment]
Hmm, but in native build, it is failing
```
[ERROR] Failures: 
[ERROR]   RouteIT>RouteTest.unstructuredFileTranscriptsAreTransformedToPojos:70 1 expectation failed.
JSON path pojos[0].customerBirthday doesn't match.
Expected: is "10 July 1986"
  Actual: 10 Jul 1986

[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

Is it related to GaalVM changes?

**Comment by ppalaga** [comment]
IIRC somebody mentioned some locale related changes in GraalVM on X. Not sure at all, what kind of they were...

**Comment by aldettinger** [comment]
Aha, 2 problems are better than 1 :)

"Jul" it looks like, short month notation, strange.

Not sure, it's related but maybe it could be tried to play with quarkus native locale:
https://camel.apache.org/camel-quarkus/3.15.x/user-guide/native-mode.html#locale

**Comment by zhfeng** [comment]
Now the native test works with adding the following configurations:

```
quarkus.native.user-country=US
quarkus.native.user-language=en
```

**Review by ppalaga — APPROVED** [review]

**Pull request merged**
