### PR TITLE
Triggering timer less often and fixing few typos

### PR DESCRIPTION
**Pull request by spatnity**
Note that the `main` branch points at the latest stable Camel Quarkus release.
Pull requests should be generally send against the `camel-quarkus-main` branch pointing at the current Camel Quarkus SNAPSHOT.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by aldettinger** [comment]
@spatnity Thanks for contribution. Wouldn't it be more robust to have the value of `period` different in test and prod environment ? Like what was done for the delay in in [DerbyDataSource](https://github.com/apache/camel-quarkus-examples/blob/main/jpa-idempotent-repository/src/test/java/org/acme/jpa/idempotent/repository/DerbyTestResource.java#L57).

**Comment by spatnity** [comment]
Can anyone give me some idea on why  some checks are failing here?

**Comment by zhfeng** [comment]
@spatnity Please see https://github.com/apache/camel-quarkus-examples/pull/182#issuecomment-1826037671 and I think we need to wait @jamesnetherton to do upgrade `main` branch after 3.6.0 is released.

**Comment by spatnity** [comment]
Thanks @zhfeng , got it!

**Comment by aldettinger** [comment]
@spatnity Meanwhile, it could be good opportunity to implement a timer  `period` different in test and prod environment ? Like what was done for the delay in in [DerbyDataSource](https://github.com/apache/camel-quarkus-examples/blob/main/jpa-idempotent-repository/src/test/java/org/acme/jpa/idempotent/repository/DerbyTestResource.java#L57).

Feel welcome to ask questions if reason to do this or implementation is not clear :)

**Comment by spatnity** [comment]
Yeah sure looking into it.

**Comment by spatnity** [comment]
@aldettinger may i know what does i mean when u say test and prod environment?
and also here in the commit, I have this https://github.com/apache/camel-quarkus-examples/pull/183/files#diff-cb496e7b34f628e54aef57972f5bf8b2a122477f942147f9b5160553218e8a91R35 
so is it required ?

**Comment by aldettinger** [comment]
@spatnity Yes sure. Let's try to explain better. In the mentioned [commit](https://github.com/apache/camel-quarkus-examples/pull/183/files#diff-cb496e7b34f628e54aef57972f5bf8b2a122477f942147f9b5160553218e8a91R35), the [period](https://camel.apache.org/components/4.0.x/timer-component.html#_endpoint_query_option_period) endpoint query option of the timer component has value `10000` ms. This is good as when we execute the route, we see messages at a human friendly pace.

However, during tests we also wait for 10s at least, it's quite long. So the idea would be to have `timer.period` value of 100ms only during tests, e.g. during `mvn clean test`. Overriding configuration during tests is a common trick commonly used. An example of such trick could be found in the `jpa-idempotent-repository` folder:

```
[main_upstream @ jpa-idempotent-repository]$ grep -R timer.period
src/main/java/org/acme/jpa/idempotent/repository/ExampleHarnessRoutes.java:        from("timer:createExampleInputFiles?delay={{timer.delay}}&period={{timer.period}}&repeatCount={{timer.repeatCount}}")
src/main/resources/application.properties:timer.period = 10000
src/test/java/org/acme/jpa/idempotent/repository/DerbyTestResource.java:                    "jdbc:derby://localhost:" + container.getMappedPort(DERBY_PORT) + "/my-db", "timer.period", "100",

```

**Pull request closed without merging**
