### PR TITLE
Add multiple datasources to Jdbc example

### PR DESCRIPTION
**Pull request by spatnity**
Note that the `main` branch points at the latest stable Camel Quarkus release.
Pull requests should be generally send against the `camel-quarkus-main` branch pointing at the current Camel Quarkus SNAPSHOT.

### CODE REVIEW

**Comment by spatnity** [comment]
Yeah `README.adoc` syntax used is different compared to others.I will update it

**Comment by spatnity** [comment]
After running this maven goal `org.l2x6.cq:cq-maven-plugin:0.33.0:update-examples-json`, there is a `examples.json` file that is getting created (Untracked) which has nothing inside it.Do i need to commit that as well?

**Comment by jamesnetherton** [comment]
You don't need to run `update-examples-json` locally. But you need to ensue that there's an entry for the new project added to [docs/modules/ROOT/attachments/examples.json](https://github.com/apache/camel-quarkus-examples/blob/camel-quarkus-main/docs/modules/ROOT/attachments/examples.json).

**Comment by aldettinger** [comment]
@spatnity Yes, it could be that. Did you needed to update the json file manually ? Or were you able to use a command ?

**Comment by jamesnetherton** [comment]
Since there's no Docker on the Windows CI runner, you'll need to add a Maven profile like this:

https://github.com/apache/camel-quarkus-examples/blob/main/jpa-idempotent-repository/pom.xml#L386-L396

**Comment by spatnity** [comment]
Done! thanks @jamesnetherton

**Review by aldettinger — APPROVED** [review]
Well done @spatnity, that's a good addition to be merged :+1: We could now redirect users to this example when they have questions around configuring multiple JDBC data sources, etl...

Please find below feedback from a local execution. If meaningful, feel welcome to fix some of them in separate prs:
 + Users might execute the docker commands from wrong directory, maybe make it clear by adding 'cd jdbc-datasource' ?
 + When the app is running logs are output each second, maybe there is a way to trigger the [timer less often](https://camel.apache.org/components/4.0.x/timer-component.html). For test, a quick timer is probably good 100ms ? For dev/jvm/native-mode probably users would expect a timer each 10s ?
 + Also when users run `mvn package` and `mvn package -D native` tests are executed. Not sure this is really useful for the demo ? maybe we could skip tests in the demo script ?
 + There is probably a typo "the resulting native executable could be start as below". Maybe "started as below" ?

**Comment by spatnity** [comment]
Thanks for the feedback @aldettinger , I will fix them

**Pull request merged**
