### PR TITLE
fix [camel-quarkus-examples] HealthTest failure on camel-quarkus-main…

### PR DESCRIPTION
**Pull request by ffang**
… branch #2711

(cherry picked from commit 4308acbf1aabedc5a416ed505abde7ca6cd53955)

Note that the `main` branch points at the latest stable Camel Quarkus release.
Pull requests should be generally send against the `camel-quarkus-main` branch pointing at the current Camel Quarkus SNAPSHOT.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by zbendhiba** [comment]
@ffang thanks on working in this issue. Maybe there are some changes to commit.

**Comment by ppalaga** [comment]
Thanks, @ffang 2ae8ee8 should fix the uncommitted changes. It is a result of running 

```
./mvnw-for-each.sh license:check net.revelc.code.formatter:formatter-maven-plugin:validate net.revelc.code:impsort-maven-plugin:check org.l2x6.cq:cq-maven-plugin:0.33.0:sync-example-properties
```

That's what the CI does as well

**Comment by ffang** [comment]
Thanks @zbendhiba @ppalaga !

**Comment by ppalaga** [comment]
Quarkus observability endpoints are now prefixed with `/q`. I guess we need a similar fix like we did in Camel Quarkus https://github.com/apache/camel-quarkus/commit/3d29121fe1dc708b57daf7f8dfef02a2269a0e41#diff-3bfaa7769a4bf24c8572497bf93008c141e1267543ec8c2757fed4fa4d607e7bR91

**Comment by ffang** [comment]
> Quarkus observability endpoints are now prefixed with `/q`. I guess we need a similar fix like we did in Camel Quarkus [apache/camel-quarkus@3d29121#diff-3bfaa7769a4bf24c8572497bf93008c141e1267543ec8c2757fed4fa4d607e7bR91](https://github.com/apache/camel-quarkus/commit/3d29121fe1dc708b57daf7f8dfef02a2269a0e41#diff-3bfaa7769a4bf24c8572497bf93008c141e1267543ec8c2757fed4fa4d607e7bR91)

Hi @ppalaga ,

FYI, it's already this case in camel-quarkus-examples HealthTest, please take a look at the testcase complete code, is it OK?
```
@Test
    public void testHealth() throws InterruptedException {
        RestAssured.get("/q/health")
                .then()
                .statusCode(200)
                .body("status", is("UP"),
                        "checks.status", containsInAnyOrder("UP", "UP"),
                        "checks.name",
                        containsInAnyOrder("camel-readiness-checks", "camel-liveness-checks"),
                        "checks.data.context", containsInAnyOrder(null, "UP"));
    }

```

Cheers
Freeman

**Comment by jamesnetherton** [comment]
> FYI, it's already this case in camel-quarkus-examples HealthTest

The same change needs to be made in the observability example project. It is still referencing the old health & metrics endpoint paths.

**Comment by ffang** [comment]
> > FYI, it's already this case in camel-quarkus-examples HealthTest
> 
> The same change needs to be made in the observability example project. It is still referencing the old health & metrics endpoint paths.

Thanks @jamesnetherton !

New commit https://github.com/apache/camel-quarkus-examples/pull/37/commits/5966eb1e9390e31c9b2c70339d515192319d8212 to fix up  observability example , please take a look!

**Comment by jamesnetherton** [comment]
Lets merge and I'll try to fix the flaky failing test in another commit.

**Comment by ffang** [comment]
Thanks @jamesnetherton !

I realized that CI failure in timer-log-main so I investigated it, which turned out to be also a health check path change issue after upgrading to Camel 3.10.
```
--- a/timer-log-main/src/test/java/org/acme/timer/TimerLogMainTest.java
+++ b/timer-log-main/src/test/java/org/acme/timer/TimerLogMainTest.java
@@ -74,7 +74,7 @@ public class TimerLogMainTest {
         try {
             int status = RestAssured.given()
                     .port(port)
-                    .get("/health")
+                    .get("/q/health")
                     .then()
                     .extract()
                     .statusCode();
```
This change can fix it, I will send another PR soon, thanks!

**Comment by ffang** [comment]
Hi @jamesnetherton,

FYI, https://github.com/apache/camel-quarkus-examples/pull/38 to fix up TimerLogMainTest.

Thanks!
Freeman

**Pull request merged**
